const menu = [
  {
    icon: 'home',
    iconType: 'icon',
    text: Home,
    link: '/',
    modalName: 'Home',
  },
  {
    icon: 'users',
    iconType: 'icon',
    text: `${String.employee}`,
    link: '/employee',
    modalName: 'Employee',
  },
  {
    icon: 'archived',
    iconType: 'icon',
    text: `${String.assets}`,
    link: '/assets',
    modalName: 'Assets',
  },
  {
    icon: 'calendar-alt',
    iconType: 'icon',
    text: `${String.leave}`,
    link: '/leave',
    modalName: 'Leave',
  },
  {
    icon: 'calendar-check',
    iconType: 'icon',
    text: `${String.grant_leave}`,
    link: '/grant-leave',
    modalName: 'GrantLeave',
  },
  {
    icon: 'calendar-booking',
    iconType: 'icon',
    text: `${String.holidays}`,
    link: '/holiday',
    modalName: 'Holiday',
  },
  {
    icon: 'swap-alt',
    iconType: 'icon',
    text: `${String.activities}`,
    link: '/company-activities',
    modalName: 'CompanyActivities',
  },
  {
    icon: 'hard-drive',
    iconType: 'icon',
    text: `${String.company_drive}`,
    link: '/company-drive',
    modalName: 'CompanyDrive',
  },
  {
    icon: 'template',
    iconType: 'icon',
    text: `${String.company_training}`,
    link: '/company-training',
    modalName: 'CompanyTraining',
  },
  {
    icon: 'file-docs',
    iconType: 'icon',
    text: `${String.company_document}`,
    link: '/company-document',
    modalName: 'CompanyDocument',
  },
  {
    icon: 'policy',
    iconType: 'icon',
    text: `${String.company_policy}`,
    link: '/company-policy',
    modalName: 'CompanyPolicy',
  },
  {
    icon: 'user',
    iconType: 'icon',
    text: `${String.master}`,
    active: false,
    modalName: 'Master',
    subMenu: [
      {
        text: `${String.assets_type}`,
        // link: '/assets/assets-type',
        link: '',
      },
      {
        text: `${String.leave_type}`,
        // link: '/leave/leave-type',
        link: '',
      },
      {
        text: `${String.holiday_type}`,
        // link: '/holiday/holiday-type',
        link: '',
      },
    ],
  },
  {
    icon: 'help',
    iconType: 'icon',
    text: `${String.help}`,
    link: '/help',
    modalName: 'CompanyHelp',
  },
]
export default menu
